import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Auth } from "aws-amplify";

export default function Home() {
  const [user, setUser] = useState(null);

  async function loginWithGoogle() {
    await Auth.federatedSignIn({ provider: "Google" });
  }

  async function logout() {
    await Auth.signOut();
  }

  useEffect(() => {
    if (!user)
      Auth.currentAuthenticatedUser()
        .then((user) => {
          setUser(user);
        })
        .catch((err) => {
          console.error(err);
        });
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {user ? (
          <button onClick={logout}>Logout</button>
        ) : (
          <button onClick={loginWithGoogle}>Login</button>
        )}
      </main>

      <pre>{JSON.stringify(user, null, 2)}</pre>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Vercel</span>
        </a>
      </footer>
    </div>
  );
}
