import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { API, graphqlOperation } from "aws-amplify";
import { addPost } from "../src/graphql/mutations";

export default function Home() {
  const [state, setState] = useState(null);

  async function handleSubmit(e) {
    e.preventDefault();

    const form = new FormData(e.target);

    const body = {
      title: form.get("title"),
      description: form.get("description"),
      views: 1,
    };

    try {
      const res = await API.graphql(
        graphqlOperation(addPost, {
          body,
        })
      );
      setState(res);
    } catch (error) {
      console.error(error);
      setState(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit}>
          <h2>Add Post</h2>
          <input type="text" placeholder="title" name="title" />
          <input type="text" placeholder="description" name="description" />
          <button type="submit">Add</button>
        </form>

        <div>
          <h2>Result:</h2>
          <pre>{JSON.stringify(state, null, 2)}</pre>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
