import React, { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { DataStore } from "aws-amplify";
import { Blog } from "../src/models";

const Home = () => {
  const [blogs, setBlogs] = useState([]);

  useEffect(() => {
    DataStore.query(Blog).then((blogs) => {
      console.log({ blogs });
      setBlogs(blogs);
    });
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();

    const form = new FormData(e.target);

    try {
      const newBlog = await DataStore.save(
        new Blog({
          name: form.get("name"),
        })
      );

      console.log({ newBlog });
    } catch (err) {
      console.error(err);
    }
  };

  const handleDelete = async (id) => {
    try {
      const deletedBlog = await DataStore.delete(Blog, id);
      console.log({ deletedBlog });
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {blogs.map(({ name, id }) => (
          <>
            <p>{name}</p>
            <button onClick={() => handleDelete(id)}>Delete</button>
          </>
        ))}

        <form onSubmit={handleSubmit}>
          <label htmlFor="name">Blog Name: </label>
          <input id="name" type="text" name="name" />
          <button type="submit">Publish</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

// export const getServerSideProps = async (context) => {
//   const { DataStore } = withSSRContext(context);

//   const fromServer = await DataStore.query(Blog);
//   console.log({ fromServer });
// };

export default Home;
