import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { Storage, withSSRContext } from "aws-amplify";
import { Blog } from "../src/models";

export async function getServerSideProps(ctx) {
  const { DataStore } = withSSRContext(ctx);
  // const blog = await DataStore.query(Blog);
  // console.log({ blog });
  const img = await Storage.get("aws.png");
  console.log({ img });

  return { props: {} };
}

export default function Home(props) {
  const uploadFile = async (e) => {
    // get file from input
    const file = e.target.files[0];

    try {
      await Storage.put(file.name, file);
    } catch (error) {
      console.error(error);
    }
  };

  const downloadFile = async () => {
    try {
      const img = await Storage.get("aws.png");
      console.log(img);
    } catch (error) {
      console.error(error);
    }
    const img = await Storage.get("aws.png");
  };

  useEffect(() => {
    downloadFile();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/about">
            <div className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Learn more about me.</p>
            </div>
          </Link>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Upload File</h2>
            <input type="file" onChange={uploadFile} />
          </a>
        </div>
      </main>

      <pre>{JSON.stringify(props, null, 2)}</pre>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
