import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import { Auth, withSSRContext } from "aws-amplify";
import styles from "../styles/Home.module.css";
import { GetServerSideProps } from "next";

type HomeProps = {
  user: {};
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { Auth } = withSSRContext(context);

  try {
    const user: any = await Auth.currentAuthenticatedUser();
    return {
      props: {
        authenticated: true,
        user: {
          username: user.username,
          email: user.attributes.email,
        },
      },
    };
  } catch (err) {
    return {
      props: {},
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
};

export const Home: React.FC = ({ user }: HomeProps): JSX.Element => {
  const signUp = async () => {
    const result = await Auth.signUp({
      username: "test",
      password: "Hello123",
      attributes: { email: "christopher.bonifacio@gmail.com" },
    });
    console.log(result);
  };

  const confirmSignUp = async () => {
    const result = await Auth.confirmSignUp("test", "718236");
    console.log(result);
  };

  const signIn = async () => {
    const result = await Auth.signIn(
      "christopher.bonifacio@gmail.com",
      "Hello123"
    );
    console.log(result);
  };

  const signOut = async () => {
    const result = await Auth.signOut();
    console.log(result);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={signUp}>Sign Up</button>
        <button onClick={confirmSignUp}>Confirm Sign Up</button>
        <button onClick={signIn}>Sign In</button>
        <button onClick={signOut}>Sign Out</button>
        <pre>User: {JSON.stringify(user, null, 2)}</pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
